import { useEffect } from "react";
import { Textarea } from "./components/ui/textarea";
import Header from "./components/Header";
import Aside from "./components/Aside";
import { useFormStore } from "./hooks/useFormStore";
import { useT } from "./hooks/useT";

function App() {
  const { prompt, result, set } = useFormStore((state) => state);

  useEffect(() => {
    document.documentElement.classList.add("dark");
  }, []);

  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex flex-1 gap-6 p-6">
        <section className="flex flex-1 flex-col gap-4">
          <div className="flex-1 grid grid-rows-2 gap-4 ">
            <Textarea
              placeholder={useT({
                pt: "Inclua o prompt para a IA",
                en: "include the prompt for AI generation",
              })}
              value={prompt}
              onChange={(e) => {
                set((state) => ({
                  ...state,
                  prompt: e.target.value,
                }));
              }}
            />
            <Textarea
              placeholder={useT({
                pt: "Resultado gerado pela IA",
                en: "Result generated by AI",
              })}
              readOnly
              value={result}
            />
          </div>
          <p className="text-sm text-muted-foreground">
            {useT({
              pt: "Lembre-se: você pode utilizar a variável",
              en: "Remember: you can use the variable",
            })}{" "}
            <code className="text-primary-foreground">{"{transcription}"}</code>{" "}
            {useT({
              pt: "no seu prompt para adicionar o conteúdo da transcrição do vídeo selecionado.",
              en: "in your prompt to add the content of the transcription of the selected video.",
            })}
          </p>
        </section>
        <Aside />
      </main>
    </div>
  );
}

export default App;
